# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisteredAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 531)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 656, 508))
        self.label.setStyleSheet("border-image: url(:/login/login_back.png);\n"
"background:transparent")
        self.label.setText("")
        self.label.setObjectName("label")
        self.register_button_confirm = QtWidgets.QPushButton(Form)
        self.register_button_confirm.setGeometry(QtCore.QRect(260, 350, 101, 51))
        self.register_button_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button_confirm.setStyleSheet("border-image: url(:/login/login_register.png);\n"
"background:transparent")
        self.register_button_confirm.setText("")
        self.register_button_confirm.setObjectName("register_button_confirm")
        self.hintmassage = QtWidgets.QLabel(Form)
        self.hintmassage.setGeometry(QtCore.QRect(220, 40, 211, 51))
        self.hintmassage.setStyleSheet("background-color: rgb(255, 240, 230);\n"
"font: 9pt \"幼圆\";\n"
"font: 18pt ;")
        self.hintmassage.setText("")
        self.hintmassage.setAlignment(QtCore.Qt.AlignCenter)
        self.hintmassage.setObjectName("hintmassage")
        self.groupBox = QtWidgets.QLabel(Form)
        self.groupBox.setGeometry(QtCore.QRect(170, 110, 331, 241))
        self.groupBox.setStyleSheet("\n"
"border-style: solid;\n"
"border-radius:15px; \n"
"background:rgba(0,0,0,0.1)")
        self.groupBox.setText("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 100, 331, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.user_register = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_register.setMinimumSize(QtCore.QSize(0, 75))
        self.user_register.setTabletTracking(True)
        self.user_register.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.user_register.setStyleSheet("border-width: 3px 3px 3px 3px;\n"
"border-image: url(:/login/login_user.png);\n"
"border-style: solid;\n"
"border-radius:10px; \n"
"border-color: rgb(255, 255, 255);\n"
"font: 20pt \"Bauhaus 93\";\n"
"background:transparent\n"
"")
        self.user_register.setText("")
        self.user_register.setAlignment(QtCore.Qt.AlignCenter)
        self.user_register.setPlaceholderText("")
        self.user_register.setObjectName("user_register")
        self.verticalLayout_3.addWidget(self.user_register)
        self.password_register = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_register.setMinimumSize(QtCore.QSize(0, 75))
        self.password_register.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password_register.setStyleSheet("border-width: 3px 3px 3px 3px;\n"
"border-image: url(:/login/login_passwprd.png);\n"
"border-style: solid;\n"
"border-radius:10px; \n"
"border-color: rgb(255, 255, 255);\n"
"font: 16pt \"Agency FB\";\n"
"background:transparent\n"
"")
        self.password_register.setText("")
        self.password_register.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_register.setAlignment(QtCore.Qt.AlignCenter)
        self.password_register.setPlaceholderText("")
        self.password_register.setObjectName("password_register")
        self.verticalLayout_3.addWidget(self.password_register)
        self.password_register2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_register2.setMinimumSize(QtCore.QSize(0, 75))
        self.password_register2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password_register2.setStyleSheet("border-width: 3px 3px 3px 3px;\n"
"border-image: url(:/login/login_passwprd.png);\n"
"border-style: solid;\n"
"border-radius:10px; \n"
"border-color: rgb(255, 255, 255);\n"
"font: 16pt \"Agency FB\";\n"
"background:transparent\n"
"")
        self.password_register2.setText("")
        self.password_register2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_register2.setAlignment(QtCore.Qt.AlignCenter)
        self.password_register2.setObjectName("password_register2")
        self.verticalLayout_3.addWidget(self.password_register2)
        self.login_back_pushbutton = QtWidgets.QPushButton(Form)
        self.login_back_pushbutton.setGeometry(QtCore.QRect(90, 110, 61, 41))
        self.login_back_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_back_pushbutton.setStyleSheet("border-image: url(:/login/register_back.png);")
        self.login_back_pushbutton.setText("")
        self.login_back_pushbutton.setObjectName("login_back_pushbutton")
        self.label.raise_()
        self.register_button_confirm.raise_()
        self.groupBox.raise_()
        self.verticalLayoutWidget.raise_()
        self.hintmassage.raise_()
        self.login_back_pushbutton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import ui.resource.rsc_rc
