# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 531)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 656, 508))
        self.label.setStyleSheet("border-image: url(:/login/login_back.png);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.login_close_pushbutton = QtWidgets.QPushButton(Form)
        self.login_close_pushbutton.setGeometry(QtCore.QRect(540, 50, 81, 71))
        self.login_close_pushbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_close_pushbutton.setStyleSheet("border-image: url(:/login/login_close.png);")
        self.login_close_pushbutton.setText("")
        self.login_close_pushbutton.setObjectName("login_close_pushbutton")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(170, 320, 101, 51))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("border-image: url(:/login/login_login.png);\n"
"\n"
"background:transparent")
        self.login_button.setText("")
        self.login_button.setObjectName("login_button")
        self.register_button = QtWidgets.QPushButton(Form)
        self.register_button.setGeometry(QtCore.QRect(370, 320, 101, 51))
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setStyleSheet("border-image: url(:/login/login_register.png);\n"
"background:transparent")
        self.register_button.setText("")
        self.register_button.setObjectName("register_button")
        self.hintmassage = QtWidgets.QLabel(Form)
        self.hintmassage.setGeometry(QtCore.QRect(220, 40, 211, 51))
        self.hintmassage.setStyleSheet("background-color: rgb(255, 240, 230);\n"
"font: 9pt \"幼圆\";\n"
"font: 18pt ;")
        self.hintmassage.setText("")
        self.hintmassage.setAlignment(QtCore.Qt.AlignCenter)
        self.hintmassage.setObjectName("hintmassage")
        self.groupBox = QtWidgets.QLabel(Form)
        self.groupBox.setGeometry(QtCore.QRect(150, 130, 351, 161))
        self.groupBox.setStyleSheet("border-style: solid;\n"
"border-radius:15px; \n"
"background:rgba(0,0,0,0.1)")
        self.groupBox.setText("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 120, 321, 202))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.user = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user.setMinimumSize(QtCore.QSize(0, 75))
        self.user.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.user.setStyleSheet("border-width: 3px 3px 3px 3px;\n"
"border-image: url(:/login/login_user.png);\n"
"border-style: solid;\n"
"border-radius:10px; \n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Bauhaus 93\";\n"
"background:transparent;\n"
"\n"
"")
        self.user.setText("")
        self.user.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setObjectName("user")
        self.verticalLayout_3.addWidget(self.user)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setMinimumSize(QtCore.QSize(0, 75))
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setStyleSheet("border-width: 3px 3px 3px 3px;\n"
"border-image: url(:/login/login_passwprd.png);\n"
"border-style: solid;\n"
"border-radius:10px; \n"
"border-color: rgb(255, 255, 255);\n"
"font: 16pt \"Agency FB\";\n"
"background:transparent\n"
"")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.verticalLayout_3.addWidget(self.password)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.label.raise_()
        self.login_close_pushbutton.raise_()
        self.login_button.raise_()
        self.register_button.raise_()
        self.groupBox.raise_()
        self.verticalLayoutWidget.raise_()
        self.hintmassage.raise_()

        self.retranslateUi(Form)
        self.login_close_pushbutton.clicked.connect(Form.close)
        self.login_close_pushbutton.clicked.connect(self.label.close)
        self.login_close_pushbutton.clicked.connect(self.login_close_pushbutton.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "记住用户名和密码"))

